
id: 09_local_taxi_scheduled
namespace: zoomcamp
description: |
  Best to add a label `backfill:true` from the UI to track executions created via a backfill.
  CSV data used here comes from: https://github.com/DataTalksClub/nyc-tlc-data/releases
  
  For Module 2 Homework (2021 data):
  - Use backfill functionality to process data from 2021-01-01 to 2021-07-31
  - Run for both yellow and green taxi types
  - Or use ForEach + Subflow to loop over Year-Month and taxi-type combinations

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: yellow

  - id: year
    type: STRING
    displayName: Year (e.g., 2020, 2021)
    defaults: "2021"

  - id: month
    type: STRING
    displayName: Month (01-12)
    defaults: "01"

variables:
  file: "{{inputs.taxi}}_tripdata_{{inputs.year}}-{{inputs.month}}.csv"
  table: "{{inputs.taxi}}_tripdata"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"
      year: "{{inputs.year}}"
      month: "{{inputs.month}}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{render(vars.file)}}.gz | gunzip > {{render(vars.file)}}

  - id: if_yellow_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'yellow'}}"
    then:
      - id: yellow_create_table
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          CREATE TABLE IF NOT EXISTS yellow_tripdata (
              unique_row_id VARCHAR(255) PRIMARY KEY,
              filename VARCHAR(255),
              VendorID VARCHAR(50),
              tpep_pickup_datetime TIMESTAMP,
              tpep_dropoff_datetime TIMESTAMP,
              passenger_count INTEGER,
              trip_distance NUMERIC,
              RatecodeID VARCHAR(50),
              store_and_fwd_flag VARCHAR(10),
              PULocationID VARCHAR(50),
              DOLocationID VARCHAR(50),
              payment_type INTEGER,
              fare_amount NUMERIC,
              extra NUMERIC,
              mta_tax NUMERIC,
              tip_amount NUMERIC,
              tolls_amount NUMERIC,
              improvement_surcharge NUMERIC,
              total_amount NUMERIC,
              congestion_surcharge NUMERIC
          );

      - id: yellow_truncate_staging
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          DROP TABLE IF EXISTS yellow_tripdata_staging;
          CREATE TABLE yellow_tripdata_staging (
              unique_row_id VARCHAR(255),
              filename VARCHAR(255),
              VendorID VARCHAR(50),
              tpep_pickup_datetime TIMESTAMP,
              tpep_dropoff_datetime TIMESTAMP,
              passenger_count INTEGER,
              trip_distance NUMERIC,
              RatecodeID VARCHAR(50),
              store_and_fwd_flag VARCHAR(10),
              PULocationID VARCHAR(50),
              DOLocationID VARCHAR(50),
              payment_type INTEGER,
              fare_amount NUMERIC,
              extra NUMERIC,
              mta_tax NUMERIC,
              tip_amount NUMERIC,
              tolls_amount NUMERIC,
              improvement_surcharge NUMERIC,
              total_amount NUMERIC,
              congestion_surcharge NUMERIC
          );

      - id: yellow_load_csv
        type: io.kestra.plugin.jdbc.postgresql.CopyIn
        from: "{{outputs.extract.outputFiles[render(vars.file)]}}"
        table: yellow_tripdata_staging
        format: CSV
        header: true
        columns:
          - VendorID
          - tpep_pickup_datetime
          - tpep_dropoff_datetime
          - passenger_count
          - trip_distance
          - RatecodeID
          - store_and_fwd_flag
          - PULocationID
          - DOLocationID
          - payment_type
          - fare_amount
          - extra
          - mta_tax
          - tip_amount
          - tolls_amount
          - improvement_surcharge
          - total_amount
          - congestion_surcharge

      - id: yellow_update_staging
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          UPDATE yellow_tripdata_staging
          SET 
            unique_row_id = MD5(CONCAT(
              COALESCE(VendorID, ''),
              COALESCE(tpep_pickup_datetime::TEXT, ''),
              COALESCE(tpep_dropoff_datetime::TEXT, ''),
              COALESCE(PULocationID, ''),
              COALESCE(DOLocationID, '')
            )),
            filename = '{{render(vars.file)}}';

      - id: yellow_merge
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          INSERT INTO yellow_tripdata
          SELECT * FROM yellow_tripdata_staging
          ON CONFLICT (unique_row_id) DO NOTHING;

  - id: if_green_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'green'}}"
    then:
      - id: green_create_table
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          CREATE TABLE IF NOT EXISTS green_tripdata (
              unique_row_id VARCHAR(255) PRIMARY KEY,
              filename VARCHAR(255),
              VendorID VARCHAR(50),
              lpep_pickup_datetime TIMESTAMP,
              lpep_dropoff_datetime TIMESTAMP,
              store_and_fwd_flag VARCHAR(10),
              RatecodeID VARCHAR(50),
              PULocationID VARCHAR(50),
              DOLocationID VARCHAR(50),
              passenger_count INTEGER,
              trip_distance NUMERIC,
              fare_amount NUMERIC,
              extra NUMERIC,
              mta_tax NUMERIC,
              tip_amount NUMERIC,
              tolls_amount NUMERIC,
              ehail_fee NUMERIC,
              improvement_surcharge NUMERIC,
              total_amount NUMERIC,
              payment_type INTEGER,
              trip_type VARCHAR(50),
              congestion_surcharge NUMERIC
          );

      - id: green_truncate_staging
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          DROP TABLE IF EXISTS green_tripdata_staging;
          CREATE TABLE green_tripdata_staging (
              unique_row_id VARCHAR(255),
              filename VARCHAR(255),
              VendorID VARCHAR(50),
              lpep_pickup_datetime TIMESTAMP,
              lpep_dropoff_datetime TIMESTAMP,
              store_and_fwd_flag VARCHAR(10),
              RatecodeID VARCHAR(50),
              PULocationID VARCHAR(50),
              DOLocationID VARCHAR(50),
              passenger_count INTEGER,
              trip_distance NUMERIC,
              fare_amount NUMERIC,
              extra NUMERIC,
              mta_tax NUMERIC,
              tip_amount NUMERIC,
              tolls_amount NUMERIC,
              ehail_fee NUMERIC,
              improvement_surcharge NUMERIC,
              total_amount NUMERIC,
              payment_type INTEGER,
              trip_type VARCHAR(50),
              congestion_surcharge NUMERIC
          );

      - id: green_load_csv
        type: io.kestra.plugin.jdbc.postgresql.CopyIn
        from: "{{outputs.extract.outputFiles[render(vars.file)]}}"
        table: green_tripdata_staging
        format: CSV
        header: true
        columns:
          - VendorID
          - lpep_pickup_datetime
          - lpep_dropoff_datetime
          - store_and_fwd_flag
          - RatecodeID
          - PULocationID
          - DOLocationID
          - passenger_count
          - trip_distance
          - fare_amount
          - extra
          - mta_tax
          - tip_amount
          - tolls_amount
          - ehail_fee
          - improvement_surcharge
          - total_amount
          - payment_type
          - trip_type
          - congestion_surcharge

      - id: green_update_staging
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          UPDATE green_tripdata_staging
          SET 
            unique_row_id = MD5(CONCAT(
              COALESCE(VendorID, ''),
              COALESCE(lpep_pickup_datetime::TEXT, ''),
              COALESCE(lpep_dropoff_datetime::TEXT, ''),
              COALESCE(PULocationID, ''),
              COALESCE(DOLocationID, '')
            )),
            filename = '{{render(vars.file)}}';

      - id: green_merge
        type: io.kestra.plugin.jdbc.postgresql.Query
        sql: |
          INSERT INTO green_tripdata
          SELECT * FROM green_tripdata_staging
          ON CONFLICT (unique_row_id) DO NOTHING;

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.jdbc.postgresql
    values:
      url: jdbc:postgresql://pgdatabase:5432/ny_taxi
      username: root
      password: root

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green
      year: "{{ trigger.date | date('yyyy') }}"
      month: "{{ trigger.date | date('MM') }}"

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 1 * *"
    inputs:
      taxi: yellow
      year: "{{ trigger.date | date('yyyy') }}"
      month: "{{ trigger.date | date('MM') }}"
